### ISSUE TITLE
Error: Cannot find module './httpClient.js'

### ISSUE THREAD

**Issue by juliankrispel** [weaviate/weaviate-javascript-client#107]
When initiating a weaviate client like so:

```js
const client = weaviate.client({
  scheme: "http",
  host: "localhost:3000",
});
```

I gett the exception  `Error: Cannot find module './httpClient.js'` originating from lib.js. There is in fact no httpClient.js and yet it is required from within lib.js

**Comment by juliankrispel** [comment]
Looks like this is is actually fixed in the latest pr which isn't yet pushed 👀

**Comment by dirkkul** [comment]
Hi,

sorry I missed you comment! Was this fixed in the altest release for you?

**Comment by dirkkul** [comment]
please make another issue in case this happens again!
