### ISSUE TITLE
ERROR - GENERATIVE AI JS COMPONENT

### ISSUE THREAD

**Issue by pdhoward** [weaviate/weaviate-javascript-client#118]
Thanks for all the heard work on the Weaviate platform. We are testing both your javascript and python sdks, and seem to keep hitting issues with the javascript component.

Our schema and db instances are here

https://product.weaviate.network/v1/schema
https://product.weaviate.network/v1/objects

We migrated ~11k item product catalog to Weaviate in order to test the generative ai capability that you recently announced

Here is the code, closely following your example to run a simple test:

```
 import weaviate from 'weaviate-client'

let url = process.env.DB
let WEAVIATE_HOST = process.env.WEAVIATE_PRODUCT_HOST
let OPEN_API_KEY = process.env.OPENAI_API_KEY

const client = weaviate.client({
  scheme: 'https',
  host: WEAVIATE_HOST,
  headers: {'X-OpenAI-Api-Key': OPEN_API_KEY},
});

// instruction for the generative module
const generateTask = '"Summarize the selected products in a table and provide prices on each"';

client.graphql
  .get()
  .withClassName('Product')
  .withFields(
    'name ' +
    `_additional {generate(groupedResult:{ task: ${generateTask} }) { groupedResult }}`
  )
  .withNearText({
    concepts: ['drill bits and drills']
  })
  .withLimit(5)
  .do()
  .then(res => {
    console.log(res)
  })
  .catch(err => {
    console.error(err)
  });

```

Here is the console error

ClientError: Cannot query field "generate" on type "ProductAdditional".: {"response":{"errors":[{"locations":[{"column":87,"line":1}],"message":"Cannot query field \"generate\" on type \"ProductAdditional\".","path":null}],"status":200,"headers":{}},"request":{"query":"{Get{Product(nearText:{concepts:[\"drill bits and drills\"]},limit:5){name _additional {generate(groupedResult:{ task: \"Summarize the selected products in a table and provide prices on each\" }) { groupedResult }}}}}"}}
    at C:\Users\patri\Desktop\gpt\gptserver\node_modules\graphql-request\dist\index.js:416:31
    at step (C:\Users\patri\Desktop\gpt\gptserver\node_modules\graphql-request\dist\index.js:67:23)
    at Object.next (C:\Users\patri\Desktop\gpt\gptserver\node_modules\graphql-request\dist\index.js:48:53)
    at fulfilled (C:\Users\patri\Desktop\gpt\gptserver\node_modules\graphql-request\dist\index.js:39:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: {
    errors: [ [Object] ],
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  },
  request: {
    query: '{Get{Product(nearText:{concepts:["drill bits and drills"]},limit:5){name _additional {generate(groupedResult:{ task: "Summarize the selected products in a table and provide prices on each" }) { groupedResult }}}}}',
    variables: undefined
  }
}

---------------------------------------

Any tips on what I might be doing wrong would be greatly appreciated

Thank you!

**Comment by byronvoorbach** [comment]
Hi @pdhoward!

Thank you for creating an issue!

The error:  `Cannot query field "generate" ` is caused by the generate module not running alongside Weaviate. Looking at your sandbox cluster, this instance Is still running on 1.17.2. Since the WCS is currently still in beta, the easiest way to get things up and running would be to create a new cluster and reindex the data.

Hope this helps!

**Comment by pdhoward** [comment]
Excellent. That worked. Thank you!
