### ISSUE TITLE
Add support for types.

### ISSUE THREAD

**Issue by anzemur** [weaviate/weaviate-javascript-client#122]
Currently, javascript client doesn't have type definitions. It would be really useful to add type definitions for development with typescript.

**Comment by dirkkul** [comment]
Hi,

we already have an issue for this [here](https://github.com/weaviate/weaviate-javascript-client/issues/19) and an open PR [here](https://github.com/weaviate/weaviate-javascript-client/pull/121).

Closing this as duplicate
