### ISSUE TITLE
Complete TS migration type conversions

### ISSUE THREAD

**Issue by parkerduckworth** [weaviate/weaviate-javascript-client#129]
The [PR](https://github.com/weaviate/weaviate-javascript-client/pull/121) which migrated this client from untyped javascript to typescript included some types, but not all of them.  Now there are a remainder of `any` types which should be assigned their proper types, where possible.

A quick way to determine where these changes need to be made can be done by grepping the repo for `: any`.

**Comment by dirkkul** [comment]
incomplete PRs that only migrate some types are also welcome :)

**Comment by parkerduckworth** [comment]
All communication regarding this issue should be moved to the new [typescript client repo](https://github.com/weaviate/typescript-client/issues/1).
