### ISSUE TITLE
Convert to Typescript?

### ISSUE THREAD

**Issue by bkoltai** [weaviate/weaviate-javascript-client#19]
Would you be open to converting this package to TS so people can get autocomplete when using the builder pattern?

**Comment by etiennedi** [comment]
Great idea. Let's investigate how big of a change that would be. But I totally see the benefits of better tooling support.

**Comment by e-001** [comment]
Conversion is a full solution, but providing typings via a declaration file would be just as useful. I'll take a stab.

**Comment by erikvullings** [comment]
@e-001 Just wondering if you are still working on a declaration file. I would be very much interested in it!

**Comment by cnadeau** [comment]
I have done the conversion, I'll create a PR within the next week. I found some part of the code that were broken according to  types I created. I'll create a different commits for conversion vs fixes.

**Comment by dirkkul** [comment]
That is very cool, looking forward to your PR!

**Comment by dirkkul** [comment]
closed by https://github.com/weaviate/weaviate-javascript-client/issues/129
Follow-up issue for missing types: https://github.com/weaviate/weaviate-javascript-client/issues/129

Thanks a bunch @cnadeau !
